#!/usr/bin/python3
import sys


def find_factors(number):
    factors = []
    for i in range(1, number + 1):
        if number % i == 0:
            factors.append(i)
    if len(factors) >= 2:
        p = factors[0]
        q = factors[-1]
        print(f"{number}={p}*{q}")

if len(sys.argv) != 2:
    print("Bad Usage\n/.factors filename")
else:

    file_name = sys.argv[1]
    file_of_number = open(file_name)
    number = file_of_number.readline()

    while number != "\n" and number != "":
        number = int(number)
        find_factors(number)
        number = file_of_number.readline()
